site_name: Gufo Err
site_description: Gufo Err Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_err/"
copyright: "&copy; 2022, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_err/
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Overview: examples/index.md
      - Global Hook: examples/global.md
      - Extended Trace: examples/globalextend.md
      - Process the Exception: examples/process.md
      - Fail-fast: examples/failfast.md
  - Reference: reference/
  - Developers' Guide:
      - Developer's Environment: environment.md
      - Building and Testing: testing.md
      - Common Tasks: devcommon.md
      - Code Quality: codequality.md
      - Code Base: codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: license.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
watch:
  - docs/
  - src/gufo/
  - examples/
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_submodules: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
