site_name: Gufo Labs Err
site_description: Gufo Labs Err Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_err/"
copyright: "&copy; 2022, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_err/
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Overview: examples/index.md
      - Global Hook: examples/global.md
      - Extended Trace: examples/globalextend.md
      - Process the Exception: examples/process.md
      - Fail-fast: examples/failfast.md
  - Reference: reference.md
  - Developers' Guide:
      - Developer's Environment: environment.md
      - Building and Testing: testing.md
      - Code Quality: codequality.md
      - Code Base: codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - FAQ: faq.md
  - Changes: changes.md
  - License: license.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - src/gufo/
        - examples/
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
